// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
		seed: 'tsx prisma/seed.ts'
	},
	datasource: {
		// Support DATABASE_URL_PROD as fallback for production migrations
		url: process.env.DATABASE_URL || process.env.DATABASE_URL_PROD || env('DATABASE_URL'),
		shadowDatabaseUrl: process.env.PRISMA_MIGRATE_SHADOW_DATABASE_URL || undefined
	}
});
